common: &common
  smoke_detector:
    key: 'smokey_key'
  ses_smtp_credentials: # email
    username: 'xxx'
    password: 'yyy'
  github:
    secret_token: 'xxyyzz' # the webhook token
    access_token: 'deadbeef' # or username & password, if you prefer
  stack_exchange:
    client_secret: 'sekrit'
    client_id: '1234'
    key: 'key'
    redirect_uri: 'https://domain.com/authentication/redirect_target'
    login_redirect_uri: 'https://domain.com/authentication/login_redirect_target'
    token_aes_key: 'random_bytes_here'
  travis_ci:
    token: 'gibberish'
  api_field_mappings:
      - api_keys.id
      - api_keys.created_at
      - api_keys.updated_at
      - api_keys.key
      - api_keys.app_name
      - api_keys.user_id
      - api_keys.github_link
      - api_tokens.id
      - api_tokens.code
      - api_tokens.api_key_id
      - api_tokens.user_id
      - api_tokens.token
      - api_tokens.created_at
      - api_tokens.updated_at
      - api_tokens.expiry
      - blacklisted_websites.id
      - blacklisted_websites.host
      - blacklisted_websites.is_active
      - blacklisted_websites.created_at
      - blacklisted_websites.updated_at
      - commit_statuses.id
      - commit_statuses.commit_sha
      - commit_statuses.status
      - commit_statuses.commit_message
      - commit_statuses.created_at
      - commit_statuses.updated_at
      - commit_statuses.ci_url
      - deletion_logs.id
      - deletion_logs.post_id
      - deletion_logs.is_deleted
      - deletion_logs.created_at
      - deletion_logs.updated_at
      - feedbacks.id
      - feedbacks.message_link
      - feedbacks.user_name
      - feedbacks.user_link
      - feedbacks.feedback_type
      - feedbacks.post_id
      - feedbacks.post_link
      - feedbacks.user_id
      - feedbacks.is_invalidated
      - feedbacks.invalidated_by
      - feedbacks.invalidated_at
      - feedbacks.chat_user_id
      - feedbacks.created_at
      - feedbacks.updated_at
      - feedbacks.is_ignored
      - feedbacks.api_key_id
      - feedbacks.chat_host
      - flags.id
      - flags.reason
      - flags.user_id
      - flags.created_at
      - flags.updated_at
      - flags.is_completed
      - flags.post_id
      - ignored_users.id
      - ignored_users.user_name
      - ignored_users.user_id
      - ignored_users.created_at
      - ignored_users.updated_at
      - ignored_users.is_ignored
      - posts.id
      - posts.title
      - posts.body
      - posts.link
      - posts.post_creation_date
      - posts.created_at
      - posts.updated_at
      - posts.site_id
      - posts.user_link
      - posts.username
      - posts.why
      - posts.user_reputation
      - posts.score
      - posts.upvote_count
      - posts.downvote_count
      - posts.stack_exchange_user_id
      - posts.is_tp
      - posts.is_fp
      - posts.is_naa
      - posts_reasons.reason_id
      - posts_reasons.post_id
      - reasons.id
      - reasons.reason_name
      - reasons.last_post_title
      - reasons.inactive
      - roles.id
      - roles.name
      - roles.resource_type
      - roles.resource_id
      - roles.created_at
      - roles.updated_at
      - sites.id
      - sites.site_name
      - sites.site_url
      - sites.site_logo
      - sites.site_domain
      - sites.created_at
      - sites.updated_at
      - smoke_detectors.id
      - smoke_detectors.last_ping
      - smoke_detectors.name
      - smoke_detectors.location
      - smoke_detectors.access_token
      - smoke_detectors.created_at
      - smoke_detectors.updated_at
      - smoke_detectors.email_date
      - stack_exchange_users.id
      - stack_exchange_users.user_id
      - stack_exchange_users.username
      - stack_exchange_users.last_api_update
      - stack_exchange_users.still_alive
      - stack_exchange_users.answer_count
      - stack_exchange_users.question_count
      - stack_exchange_users.reputation
      - stack_exchange_users.created_at
      - stack_exchange_users.updated_at
      - stack_exchange_users.site_id
      - users.id
      - users.username
      - users.stackexchange_chat_id
      - users.meta_stackexchange_chat_id
      - users.stackoverflow_chat_id
      - users.stack_exchange_account_id
      - users_roles.user_id
      - users_roles.role_id
      - posts.deleted_at
      - posts.revision_count
      - moderator_sites.id
      - moderator_sites.user_id
      - moderator_sites.site_id
      - moderator_sites.created_at
      - moderator_sites.updated_at

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
