common: &common
  smoke_detector:
    key: 'smokey_key'
  ses_smtp_credentials: # email
    username: 'xxx'
    password: 'yyy'
  aws:
    access_token: ''
    secret_token: ''
  github:
    secret_token: 'xxyyzz' # the webhook token
    access_token: 'deadbeef' # or username & password, if you prefer
  stack_exchange:
    client_secret: 'sekrit'
    client_id: '1234'
    key: 'key'
    redirect_uri: 'https://domain.com/authentication/redirect_target'
    login_redirect_uri: 'https://domain.com/authentication/login_redirect_target'
    token_aes_key: 'random_bytes_here'
  travis_ci:
    token: 'gibberish'
  api_field_mappings:
    - announcements.id
    - announcements.text
    - announcements.expiry
    - announcements.created_at
    - announcements.updated_at
    - api_keys.id
    - api_keys.created_at
    - api_keys.updated_at
    - api_keys.app_name
    - api_keys.user_id
    - api_keys.github_link
    - api_keys.is_trusted
    - audits.id
    - audits.auditable_id
    - audits.auditable_type
    - audits.associated_id
    - audits.associated_type
    - audits.user_id
    - audits.user_type
    - audits.username
    - audits.action
    - audits.audited_changes
    - audits.version
    - audits.comment
    - audits.created_at
    - commit_statuses.id
    - commit_statuses.commit_sha
    - commit_statuses.status
    - commit_statuses.commit_message
    - commit_statuses.created_at
    - commit_statuses.updated_at
    - commit_statuses.ci_url
    - deletion_logs.id
    - deletion_logs.post_id
    - deletion_logs.is_deleted
    - deletion_logs.created_at
    - deletion_logs.updated_at
    - deletion_logs.api_key_id
    - domain_tags.id
    - domain_tags.name
    - domain_tags.description
    - domain_tags.created_at
    - domain_tags.updated_at
    - feedbacks.id
    - feedbacks.message_link
    - feedbacks.user_name
    - feedbacks.user_link
    - feedbacks.feedback_type
    - feedbacks.post_id
    - feedbacks.post_link
    - feedbacks.user_id
    - feedbacks.is_invalidated
    - feedbacks.invalidated_by
    - feedbacks.invalidated_at
    - feedbacks.chat_user_id
    - feedbacks.created_at
    - feedbacks.updated_at
    - feedbacks.api_key_id
    - feedbacks.chat_host
    - flag_conditions.id
    - flag_conditions.flags_enabled
    - flag_conditions.min_weight
    - flag_conditions.max_poster_rep
    - flag_conditions.min_reason_count
    - flag_conditions.user_id
    - flag_conditions.created_at
    - flag_conditions.updated_at
    - flag_logs.id
    - flag_logs.success
    - flag_logs.error_message
    - flag_logs.flag_condition_id
    - flag_logs.user_id
    - flag_logs.post_id
    - flag_logs.created_at
    - flag_logs.updated_at
    - flag_logs.is_dry_run
    - flag_logs.backoff
    - flag_logs.site_id
    - flag_logs.is_auto
    - flag_logs.api_key_id
    - flag_settings.id
    - flag_settings.name
    - flag_settings.value
    - flag_settings.created_at
    - flag_settings.updated_at
    - moderator_sites.id
    - moderator_sites.user_id
    - moderator_sites.site_id
    - moderator_sites.created_at
    - moderator_sites.updated_at
    - posts.id
    - posts.title
    - posts.body
    - posts.link
    - posts.post_creation_date
    - posts.created_at
    - posts.updated_at
    - posts.site_id
    - posts.user_link
    - posts.username
    - posts.why
    - posts.user_reputation
    - posts.score
    - posts.upvote_count
    - posts.downvote_count
    - posts.stack_exchange_user_id
    - posts.is_tp
    - posts.is_fp
    - posts.is_naa
    - posts.revision_count
    - posts.deleted_at
    - posts.smoke_detector_id
    - posts.autoflagged
    - reasons.id
    - reasons.reason_name
    - reasons.last_post_title
    - reasons.inactive
    - reasons.weight
    - reasons.maximum_weight
    - roles.id
    - roles.name
    - roles.resource_type
    - roles.resource_id
    - roles.created_at
    - roles.updated_at
    - sites.id
    - sites.site_name
    - sites.site_url
    - sites.site_logo
    - sites.site_domain
    - sites.created_at
    - sites.updated_at
    - sites.flags_enabled
    - sites.max_flags_per_post
    - sites.is_child_meta
    - sites.last_users_update
    - smoke_detectors.id
    - smoke_detectors.last_ping
    - smoke_detectors.name
    - smoke_detectors.location
    - smoke_detectors.created_at
    - smoke_detectors.updated_at
    - smoke_detectors.email_date
    - smoke_detectors.user_id
    - smoke_detectors.is_standby
    - smoke_detectors.force_failover
    - spam_domains.id
    - spam_domains.domain
    - spam_domains.whois
    - spam_domains.created_at
    - spam_domains.updated_at
    - stack_exchange_users.id
    - stack_exchange_users.user_id
    - stack_exchange_users.username
    - stack_exchange_users.last_api_update
    - stack_exchange_users.still_alive
    - stack_exchange_users.answer_count
    - stack_exchange_users.question_count
    - stack_exchange_users.reputation
    - stack_exchange_users.created_at
    - stack_exchange_users.updated_at
    - stack_exchange_users.site_id
    - statistics.id
    - statistics.posts_scanned
    - statistics.smoke_detector_id
    - statistics.created_at
    - statistics.updated_at
    - statistics.api_quota
    - statistics.post_scan_rate
    - user_site_settings.id
    - user_site_settings.max_flags
    - user_site_settings.flags_used
    - user_site_settings.user_id
    - user_site_settings.created_at
    - user_site_settings.updated_at
    - users.id
    - users.remember_created_at
    - users.created_at
    - users.updated_at
    - users.username
    - users.stackexchange_chat_id
    - users.meta_stackexchange_chat_id
    - users.stackoverflow_chat_id
    - users.stack_exchange_account_id
    - users.flags_enabled
    - users.enabled_2fa
    - users.announcement_emails
    - users.oauth_created
    - post_comments.id
    - post_comments.post_id
    - post_comments.user_id
    - post_comments.text
    - post_comments.created_at
    - post_comments.updated_at
  sensitive_fields:
    - api_keys.key
    - api_tokens.code
    - api_tokens.token
    - audits.remote_address
    - audits.request_uuid
    - flags.reason
    - flags.user_id
    - github_tokens.token
    - ignored_users.user_name
    - ignored_users.user_id
    - smoke_detectors.access_token
    - users.email
    - users.encrypted_password
    - users.reset_password_token
    - users.reset_password_sent_at
    - users.encrypted_api_token
    - users.two_factor_token
    - users.salt
    - users.iv

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
